---
- name: Install Vector
  hosts: clickhouse
  handlers:
    - name: Start vector service
      become: true
      ansible.builtin.service:
        name: vector-server
        state: restarted
  tasks:
  - name: Create Directories
    file:
      path: "{{ item }}"
      state: directory
      owner: root
      group: root
      mode: 0755
    loop:
      - '/vector/'

    # - block:
  - name: Get vector distrib
    ansible.builtin.get_url:
      # url: "https://packages.clickhouse.com/rpm/stable/{{ item }}-{{ clickhouse_version }}.noarch.rpm"
      url: "https://packages.timber.io/vector/{{ vector_version }}/vector-{{ vector_version }}-x86_64-unknown-linux-musl.tar.gz"
      dest: "/vector/vector-{{ clickhouse_version }}.tar.gz"

  - name: Unpack vector
    unarchive:
      src: "/vector/vector-{{ clickhouse_version }}.tar.gz"
      dest: "/vector/"
      remote_src: yes


    # - name: Install clickhouse packages
    #   become: true
    #   ansible.builtin.yum:
    #     name:
    #       - clickhouse-common-static-{{ clickhouse_version }}.rpm
    #       - clickhouse-client-{{ clickhouse_version }}.rpm
    #       - clickhouse-server-{{ clickhouse_version }}.rpm
    #   notify: Start clickhouse service
    # - name: Flush handlers
    #   meta: flush_handlers
    # - name: Create database
    #   ansible.builtin.command: "clickhouse-client -q 'create database logs;'"
    #   register: create_db
    #   failed_when: create_db.rc != 0 and create_db.rc !=82
    #   changed_when: create_db.rc == 0